# Generated by Django 5.0.3 on 2024-03-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_remove_routeinstance_route_route_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='state',
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Preparado'), ('c', 'En camino'), ('e', 'Entregado'), ('r', 'Recibido')], default='p', help_text='Estado', max_length=1),
        ),
        migrations.AddField(
            model_name='route',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RouteInstance',
        ),
    ]
