# Generated by Django 5.0.3 on 2024-04-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_remove_route_state_route_status_route_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='barcode',
            field=models.PositiveBigIntegerField(verbose_name='Codigo de Barra'),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Preparado'), ('c', 'En camino'), ('e', 'Entregado'), ('r', 'Recibido')], default='p', max_length=1, verbose_name='Estado'),
        ),
    ]
