# Generated by Django 5.0.3 on 2024-04-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_remove_route_status_remove_route_time_routeinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeinstance',
            old_name='id_route',
            new_name='route',
        ),
    ]
