# Generated by Django 5.0.3 on 2024-04-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_rename_id_route_routeinstance_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_date',
            field=models.DateField(blank=True, default='09-04-2024', null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='time',
            field=models.DateField(blank=True, default='09-04-2024', null=True),
        ),
    ]
