# Generated by Django 5.0.3 on 2024-04-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_alter_route_preparation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinstance',
            name='time',
            field=models.DateField(blank=True, default='09/04/2024', null=True),
        ),
    ]
