# Generated by Django 5.0.3 on 2024-04-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0009_alter_route_preparation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeinstance',
            options={'ordering': ['-isinstance_date']},
        ),
        migrations.RenameField(
            model_name='routeinstance',
            old_name='time',
            new_name='isinstance_date',
        ),
        migrations.AddField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='21:07:58', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AddField(
            model_name='routeinstance',
            name='isinstance_time',
            field=models.TimeField(blank=True, default='21:07:58', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
