# Generated by Django 5.0.3 on 2024-04-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_alter_routeinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-preparation_date']},
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_date',
            field=models.DateField(blank=True, default='2024-04-09', null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='21:21:51', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='isinstance_date',
            field=models.DateField(blank=True, default='2024-04-09', null=True),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='isinstance_time',
            field=models.TimeField(blank=True, default='21:21:51', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
