# Generated by Django 5.0.3 on 2024-04-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_alter_route_preparation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='state',
            field=models.CharField(default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='12:45:56', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='isinstance_time',
            field=models.TimeField(blank=True, default='12:45:56', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
