# Generated by Django 5.0.3 on 2024-04-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0013_route_state_alter_route_preparation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='14:15:10', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='state',
            field=models.CharField(blank=True, default='p', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='isinstance_time',
            field=models.TimeField(blank=True, default='14:15:10', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
