# Generated by Django 5.0.3 on 2024-04-12 22:51

import django.db.models.deletion
import route.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0015_alter_route_preparation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='19:51:03', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='isinstance_time',
            field=models.TimeField(blank=True, default='19:51:03', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='route',
            field=models.ForeignKey(default=route.models.Route, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.route'),
        ),
    ]
