# Generated by Django 5.0.3 on 2024-04-14 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0020_alter_route_preparation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_date',
            field=models.DateField(blank=True, default='2024-04-13', null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='21:57:57', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='isinstance_date',
            field=models.DateField(blank=True, default='2024-04-13', null=True),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='isinstance_time',
            field=models.TimeField(blank=True, default='21:57:57', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.route'),
        ),
    ]
