# Generated by Django 5.0.3 on 2024-04-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0022_alter_route_preparation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeinstance',
            options={'ordering': ['-instance_date']},
        ),
        migrations.RenameField(
            model_name='routeinstance',
            old_name='isinstance_date',
            new_name='instance_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='route',
            name='state',
        ),
        migrations.RemoveField(
            model_name='routeinstance',
            name='isinstance_time',
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Preparado'), ('c', 'En camino'), ('e', 'Entregado'), ('r', 'Recibido')], default='p', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='09:45:41', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='09:45:41', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.DeleteModel(
            name='UserOrigin',
        ),
    ]
