# Generated by Django 5.0.3 on 2024-04-22 14:03

import builtins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0025_alter_route_preparation_time_alter_route_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='11:03:54', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.OneToOneField(default=builtins.isinstance, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='11:03:54', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
