# Generated by Django 5.0.3 on 2024-04-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0031_alter_route_preparation_time_alter_route_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='20:49:49', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='20:49:49', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
