# Generated by Django 5.0.3 on 2024-06-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0042_alter_route_preparation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='10:43:07', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='10:43:07', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
