# Generated by Django 5.0.6 on 2024-06-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0045_alter_route_preparation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='16:47:28', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='16:47:28', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
