# Generated by Django 5.1 on 2024-08-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0050_alter_route_options_alter_route_preparation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='01:28:18', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='01:28:18', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
