# Generated by Django 5.1 on 2024-09-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0061_alter_route_preparation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='15:30:03', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='15:30:03', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='states',
            name='state',
            field=models.IntegerField(),
        ),
    ]
