# Generated by Django 5.1 on 2024-09-28 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0064_alter_route_preparation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printernode',
            name='state',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.states'),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='23:16:13', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='23:16:13', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
