# Generated by Django 5.1 on 2024-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0069_alter_route_preparation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_date',
            field=models.DateField(blank=True, default='2024-10-02', null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='19:34:41', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_date',
            field=models.DateField(blank=True, default='2024-10-02', null=True),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='19:34:41', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
