# Generated by Django 5.1 on 2024-10-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0070_perfil_dealer_alter_route_preparation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.nodeorigin'),
        ),
        migrations.AlterField(
            model_name='route',
            name='preparation_time',
            field=models.TimeField(blank=True, default='19:39:32', null=True, verbose_name='Hora de Creacion'),
        ),
        migrations.AlterField(
            model_name='routeinstance',
            name='instance_time',
            field=models.TimeField(blank=True, default='19:39:32', null=True, verbose_name='Hora de Creacion'),
        ),
    ]
